package com.ak.store.catalogueSagaWorker.model.inbox;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum InboxEventType {
    ADD_PRODUCT_GRADE("ADD_PRODUCT_GRADE"),
    REMOVE_PRODUCT_GRADE("REMOVE_PRODUCT_GRADE"),

    UPDATE_PRODUCT_GRADE("UPDATE_PRODUCT_GRADE"),
    CANCEL_UPDATE_PRODUCT_GRADE("CANCEL_UPDATE_PRODUCT_GRADE"),

    DELETE_PRODUCT_GRADE("DELETE_PRODUCT_GRADE"),
    CANCEL_DELETE_PRODUCT_GRADE("CANCEL_DELETE_PRODUCT_GRADE"),

    CANCEL_PRODUCT_CREATED("CANCEL_PRODUCT_CREATED"),
    CONFIRM_PRODUCT_CREATED("CONFIRM_PRODUCT_CREATED");

    private final String value;
}
