package com.ak.store.catalogueOutbox.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum OutboxEventType {
    PRODUCT_CREATED("PRODUCT_CREATED"),
    CANCEL_PRODUCT_CREATED("CANCEL_PRODUCT_CREATED"),
    CONFIRM_PRODUCT_CREATED("CONFIRM_PRODUCT_CREATED"),

    PRODUCT_UPDATED("PRODUCT_UPDATED"),
    PRODUCT_DELETED("PRODUCT_DELETED"),

    CATEGORY_CREATED("CATEGORY_CREATED"),
    CATEGORY_UPDATED("CATEGORY_UPDATED"),
    CATEGORY_DELETED("CATEGORY_DELETED"),

    CHARACTERISTIC_CREATED("CHARACTERISTIC_CREATED"),
    CHARACTERISTIC_UPDATED("CHARACTERISTIC_UPDATED"),
    CHARACTERISTIC_DELETED("CHARACTERISTIC_DELETED"),

    ADD_PRODUCT_GRADE("ADD_PRODUCT_GRADE"),
    REMOVE_PRODUCT_GRADE("REMOVE_PRODUCT_GRADE"),

    UPDATE_PRODUCT_GRADE("UPDATE_PRODUCT_GRADE"),
    CANCEL_UPDATE_PRODUCT_GRADE("CANCEL_UPDATE_PRODUCT_GRADE"),

    DELETE_PRODUCT_GRADE("DELETE_PRODUCT_GRADE"),
    CANCEL_DELETE_PRODUCT_GRADE("CANCEL_DELETE_PRODUCT_GRADE");

    private final String value;
}