package com.ak.store.reviewOutbox.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum OutboxEventType {
    REVIEW_CREATION("REVIEW_CREATION"),
    CONFIRM_REVIEW_CREATION("CONFIRM_REVIEW_CREATION"),
    CANCEL_REVIEW_CREATION("CANCEL_REVIEW_CREATION"),

    REVIEW_UPDATE("REVIEW_UPDATE"),
    CONFIRM_REVIEW_UPDATE("CONFIRM_REVIEW_UPDATE"),
    CANCEL_REVIEW_UPDATE("CANCEL_REVIEW_UPDATE"),

    REVIEW_DELETION("REVIEW_DELETION"),
    CONFIRM_REVIEW_DELETION("CONFIRM_REVIEW_DELETION"),
    CANCEL_REVIEW_DELETION("CANCEL_REVIEW_DELETION");

    private final String value;
}